root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/api"
  bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html", "mod", "sum"]
  include_dir = [".", "cmd", "internal"]
  exclude_dir = ["tmp", "vendor", "node_modules", ".git"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  kill_delay = "1s"
  log = "build-errors.log"
  poll = true
  poll_interval = 250
  delay = 300
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = false
  watch_delay = 0
